-- Neutralized: coordinates must be saved only by the admin table-map calibrator.
-- This migration intentionally does not insert, update, upsert, or recalibrate
-- rows in public.official_table_map_places.
